# -*- coding: utf-8 -*-
"""GCP_Vision Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L664ME07SbERsrAMFbP65JXGYXq8yw6M
"""

pip install google-cloud-vision

import os

os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = "/content/peak-woodland-429012-c0-59ac7782714e.json"

from google.cloud import vision
import io

def analyze_image(image_path):
    # Initialize the Vision client
    client = vision.ImageAnnotatorClient()

    # Load the image file
    with io.open(image_path, 'rb') as image_file:
        content = image_file.read()

    # Prepare the image for analysis
    image = vision.Image(content=content)

    # Perform label detection on the image file
    response = client.label_detection(image=image)
    labels = response.label_annotations

    # Print the detected labels
    print('Labels:')
    for label in labels:
        print(f'{label.description} (confidence: {label.score:.2f})')

# Path to the image file
image_path = '/content/imagee.jpg'

# Analyze the image
analyze_image(image_path)

